# Generated by Django 3.1.7 on 2021-05-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20210518_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Buyer_Name', models.CharField(max_length=200)),
                ('Mobile', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Product_Name', models.CharField(max_length=200)),
                ('Purchase_Value', models.CharField(max_length=200)),
                ('Date_of_Purchase', models.CharField(max_length=200)),
                ('order_id', models.CharField(max_length=200)),
                ('Platform', models.CharField(max_length=200)),
                ('Upi', models.CharField(max_length=200)),
            ],
        ),
    ]
