# Generated by Django 3.1.7 on 2021-05-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_cashback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Mobile', models.CharField(max_length=40)),
                ('Email', models.CharField(max_length=40)),
                ('Subject', models.CharField(max_length=40)),
                ('Description', models.CharField(max_length=40)),
            ],
        ),
    ]
